# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Climate.destroy_all

Climate.create([
  {climate_code: "1", climate: "Equatorial Climates"},
  {climate_code: "1.1", climate: "Equatorial rainforest, fully humid"},
  {climate_code: "1.1.1", climate: "Equatorial rainforest, fully humid"},
  {climate_code: "1.2", climate: "Equatorial monsoon"},
  {climate_code: "1.2.1", climate: "Equatorial monsoon"},
  {climate_code: "1.3", climate: "Equatorial savannah with dry summer"},
  {climate_code: "1.3.1", climate: "Equatorial savannah with dry summer"},
  {climate_code: "1.4", climate: "Equatorial savannah with dry winter"},
  {climate_code: "1.4.1", climate: "Equatorial savannah with dry winter"},
  {climate_code: "2", climate: "Arid climates"},
  {climate_code: "2.1", climate: "Desert climate"},
  {climate_code: "2.1.1", climate: "Hot desert"},
  {climate_code: "2.1.2", climate: "Cold desert"},
  {climate_code: "2.1.3", climate: "Hot steppe"},
  {climate_code: "2.1.4", climate: "Cold steppe"},
  {climate_code: "2.2", climate: "Steppe climate"},
  {climate_code: "3", climate: "Warm temperate climates"},
  {climate_code: "3.1", climate: "Warm temperate climate, fully humid"},
  {climate_code: "3.1.1", climate: "Hot summer"},
  {climate_code: "3.1.2", climate: "Warm summer"},
  {climate_code: "3.1.3", climate: "Cool summer and cold winter"},
  {climate_code: "3.2", climate: "Warm temperate climate with dry summer"},
  {climate_code: "3.2.1", climate: "Hot summer"},
  {climate_code: "3.2.2", climate: "Warm summer"},
  {climate_code: "3.2.3", climate: "Cool summer and cold winter"},
  {climate_code: "3.3", climate: "Warm temperate climate with dry winter"},
  {climate_code: "3.3.1", climate: "Hot summer"},
  {climate_code: "3.3.2", climate: "Warm summer"},
  {climate_code: "3.3.3", climate: "Cool summer and cold winter"},
  {climate_code: "4", climate: "Snow climates"},
  {climate_code: "4.1", climate: "Snow climate, fully humid"},
  {climate_code: "4.1.1", climate: "Hot summer"},
  {climate_code: "4.1.2", climate: "Warm summer"},
  {climate_code: "4.1.3", climate: "Cool summer and cold winter"},
  {climate_code: "4.1.4", climate: "extremely continental"},
  {climate_code: "4.2", climate: "Snow climate with dry winter"},
  {climate_code: "4.2.1", climate: "Hot summer"},
  {climate_code: "4.2.2", climate: "Warm summer"},
  {climate_code: "4.2.3", climate: "Cool summer and cold winter"},
  {climate_code: "4.2.4", climate: "extremely continental"},
  {climate_code: "4.3", climate: "Snow climate with dry summer"},
  {climate_code: "4.3.1", climate: "Hot summer"},
  {climate_code: "4.3.2", climate: "Warm summer"},
  {climate_code: "4.3.3", climate: "Cool summer and cold winter"},
  {climate_code: "4.3.4", climate: "extremely continental"},
  {climate_code: "5", climate: "Polar climates"},
  {climate_code: "5.1", climate: "Tundra climate"},
  {climate_code: "5.1.1", climate: "Tundra climate"},
  {climate_code: "5.2", climate: "Frost climate"},
  {climate_code: "5.2.1", climate: "Frost climate"}
])

Landuse.destroy_all

Landuse.create([
  {landuse_code: "1", landuse: "Artificial surfaces"},
  {landuse_code: "1.1", landuse: "Urban fabric"},
  {landuse_code: "1.1.1", landuse: "Continuous urban fabric"},
  {landuse_code: "1.1.2", landuse: "Discontinuous urban fabric"},
  {landuse_code: "1.2", landuse: "Industrial, commercial and transport units"},
  {landuse_code: "1.2.1", landuse: "Industrial or commercial units"},
  {landuse_code: "1.2.2", landuse: "Road and rail networks and associated land"},
  {landuse_code: "1.2.3", landuse: "Port areas"},
  {landuse_code: "1.2.4", landuse: "Airports"},
  {landuse_code: "1.3", landuse: "Mine, dump and construction sites"},
  {landuse_code: "1.3.1", landuse: "Mineral extraction sites"},
  {landuse_code: "1.3.2", landuse: "Dump sites"},
  {landuse_code: "1.3.3", landuse: "Construction sites"},
  {landuse_code: "1.4", landuse: "Artificial, non-agricultural vegetated areas"},
  {landuse_code: "1.4.1", landuse: "Green urban areas"},
  {landuse_code: "1.4.2", landuse: "Sport and leisure facilities"},
  {landuse_code: "2", landuse: "Agricultural areas"},
  {landuse_code: "2.1", landuse: "Arable land"},
  {landuse_code: "2.1.1", landuse: "Non-irrigated arable land"},
  {landuse_code: "2.1.2", landuse: "Permanently irrigated land"},
  {landuse_code: "2.1.3", landuse: "Rice fields"},
  {landuse_code: "2.2", landuse: "Permanent crops"},
  {landuse_code: "2.2.1", landuse: "Vineyards"},
  {landuse_code: "2.2.2", landuse: "Fruit trees and berry plantations"},
  {landuse_code: "2.2.3", landuse: "Olive groves"},
  {landuse_code: "2.3", landuse: "Pastures"},
  {landuse_code: "2.3.1", landuse: "Pastures"},
  {landuse_code: "2.4", landuse: "Heterogeneous agricultural areas"},
  {landuse_code: "2.4.1", landuse: "Annual crops associated with permanent crops"},
  {landuse_code: "2.4.2", landuse: "Complex cultivation patterns"},
  {landuse_code: "2.4.3", landuse: "Land principally occupied by agriculture, with significant areas of natural vegetation"},
  {landuse_code: "2.4.4", landuse: "Agro-forestry areas"},
  {landuse_code: "3", landuse: "Forest and semi natural areas"},
  {landuse_code: "3.1", landuse: "Forests"},
  {landuse_code: "3.1.1", landuse: "Broad-leaved forest"},
  {landuse_code: "3.1.2", landuse: "Coniferous forest"},
  {landuse_code: "3.1.3", landuse: "Mixed forest"},
  {landuse_code: "3.2", landuse: "Scrub and/or herbaceous vegetation associations"},
  {landuse_code: "3.2.1", landuse: "Natural grasslands"},
  {landuse_code: "3.2.2", landuse: "Moors and heathland"},
  {landuse_code: "3.2.3", landuse: "Sclerophyllous vegetation"},
  {landuse_code: "3.2.4", landuse: "Transitional woodland-shrub"},
  {landuse_code: "3.3", landuse: "Open spaces with little or no vegetation"},
  {landuse_code: "3.3.1", landuse: "Beaches, dunes, sands"},
  {landuse_code: "3.3.2", landuse: "Bare rocks"},
  {landuse_code: "3.3.3", landuse: "Sparsely vegetated areas"},
  {landuse_code: "3.3.4", landuse: "Burnt areas"},
  {landuse_code: "3.3.5", landuse: "Glaciers and perpetual snow"},
  {landuse_code: "4", landuse: "Wetlands"},
  {landuse_code: "4.1", landuse: "Inland wetlands"},
  {landuse_code: "4.1.1", landuse: "Inland marshes"},
  {landuse_code: "4.1.2", landuse: "Peat bogs"},
  {landuse_code: "4.2", landuse: "Maritime wetlands"},
  {landuse_code: "4.2.1", landuse: "Salt marshes"},
  {landuse_code: "4.2.2", landuse: "Salines"},
  {landuse_code: "4.2.3", landuse: "Intertidal flats"},
  {landuse_code: "5", landuse: "Water bodies"},
  {landuse_code: "5.1", landuse: "Inland waters"},
  {landuse_code: "5.1.1", landuse: "Water courses"},
  {landuse_code: "5.1.2", landuse: "Water bodies"},
  {landuse_code: "5.2", landuse: "Marine waters"},
  {landuse_code: "5.2.1", landuse: "Coastal lagoons"},
  {landuse_code: "5.2.2", landuse: "Estuaries"},
  {landuse_code: "5.2.3", landuse: "Sea and ocean"}
])

Plantcommunity.destroy_all

Plantcommunity.create([
  {plantcommunity_code: "1",   plantcommunity: "Bosque denso (arboles de mas de 5m cuyas copas se tocan)"},
  {plantcommunity_code: "1.1", plantcommunity: "Mayormente sempervirente"},
  {plantcommunity_code: "1.2", plantcommunity: "Mayormente deciduo"},
  {plantcommunity_code: "1.3", plantcommunity: "Extremadamente xeromórfico"},
  {plantcommunity_code: "2",   plantcommunity: "Bosque claro (Comunidad de árboles abierta)"},
  {plantcommunity_code: "2.1", plantcommunity: "Mayormente sempervirente"},
  {plantcommunity_code: "2.2", plantcommunity: "Mayormente deciduo"},
  {plantcommunity_code: "2.3", plantcommunity: "Extremadamente xeromórfico"},
  {plantcommunity_code: "3",   plantcommunity: "Matorral (denso o claro)"},
  {plantcommunity_code: "3.1", plantcommunity: "Mayormente sempervirente"},
  {plantcommunity_code: "3.2", plantcommunity: "Sempervirente aciculifoliado micrófilo claro (o denso)"},
  {plantcommunity_code: "3.3", plantcommunity: "Mayormente deciduo"},
  {plantcommunity_code: "3.4", plantcommunity: "Extremadamente xeromórfico (subdesierto)"},
  {plantcommunity_code: "4",   plantcommunity: "Matorral enano y comunidades relacionadas"},
  {plantcommunity_code: "4.1", plantcommunity: "Matorral enano mayormente sempervirente"},
  {plantcommunity_code: "4.2", plantcommunity: "Matorral enano mayormente deciduo"},
  {plantcommunity_code: "4.3", plantcommunity: "Matorral claro enano extremadamente xeromórfico"},
  {plantcommunity_code: "4.4", plantcommunity: "Tundra de arbustos enanos, líquenes y musgos"},
  {plantcommunity_code: "4.5", plantcommunity: "Formación de pantano turboso de musgos con arbustos enanos"},
  {plantcommunity_code: "5",   plantcommunity: "Vegetación herbácea"},
  {plantcommunity_code: "5.1", plantcommunity: "Vegetación graminoide alta"},
  {plantcommunity_code: "5.2", plantcommunity: "Vegetación graminoide de altura intermedia"},
  {plantcommunity_code: "5.3", plantcommunity: "Vegetación graminoide baja"},
  {plantcommunity_code: "5.4", plantcommunity: "Vegetación de forbias"},
  {plantcommunity_code: "5.5", plantcommunity: "Vegetación hidromórfica de agua dulce"}

])

Hib.destroy_all

Hib.create([
  {hib_code: "1",   hib: "Alteration of habitat"},
  {hib_code: "1.1", hib: "Destruction of habitats"},
  {hib_code: "1.2", hib: "Creation of habitats"},
  {hib_code: "1.3", hib: "Fragmentation of habitats"},
  {hib_code: "1.4", hib: "Others"},
  {hib_code: "2",   hib: "Alteration of resource flows"},
  {hib_code: "2.1", hib: "Reduction in net primary production"},
  {hib_code: "2.2", hib: "Increase in temperature"},
  {hib_code: "2.3", hib: "Mobilization and concentration of nutrients"},
  {hib_code: "2.4", hib: "Dispersion of toxins"},
  {hib_code: "2.5", hib: "Dispersions of water and changes in the timing of water availability"},
  {hib_code: "2.6", hib: "Degradation of water quality"},
  {hib_code: "2.7", hib: "Others"},
  {hib_code: "3",   hib: "Alteration of disturbance regimes"},
  {hib_code: "3.1", hib: "Increase in frequency and /or intensity of natural disturbances"},
  {hib_code: "3.2", hib: "Reduction in frequency and /or intensity of natural disturbances"},
  {hib_code: "3.3", hib: "Others"},
  {hib_code: "4",   hib: "Alteration of species composition"},
  {hib_code: "4.1", hib: "Preferential destruction or promotion of native species"},
  {hib_code: "4.2", hib: "Introduction of nonnative species"},
  {hib_code: "4.3", hib: "Others"}

])

Ptrait.destroy_all

Ptrait.create([
  {ptrait_code: "1", ptrait: "Vegetative Traits"},
  {ptrait_code: "1.1", ptrait: "Whole plant traits"},
  {ptrait_code: "1.1.1", ptrait: "Growth form"},
  {ptrait_code: "1.1.10", ptrait: "root-shoot ratio"},
  {ptrait_code: "1.1.11", ptrait: "Above-ground biomass"},
  {ptrait_code: "1.1.12", ptrait: "Below-Ground Biomass"},
  {ptrait_code: "1.1.13", ptrait: "Plant strategy (CSR)"},
  {ptrait_code: "1.1.14", ptrait: "Others"},
  {ptrait_code: "1.1.2", ptrait: "Lifespan or life history"},
  {ptrait_code: "1.1.3", ptrait: "Life form"},
  {ptrait_code: "1.1.4", ptrait: "Plant height"},
  {ptrait_code: "1.1.5", ptrait: "Canopy height"},
  {ptrait_code: "1.1.6", ptrait: "Clonality"},
  {ptrait_code: "1.1.7", ptrait: "Spinescence"},
  {ptrait_code: "1.1.8", ptrait: "Flammability"},
  {ptrait_code: "1.1.9", ptrait: "Total plant biomass"},
  {ptrait_code: "1.2", ptrait: "Leaf traits"},
  {ptrait_code: "1.2.1", ptrait: "Specific leaf area"},
  {ptrait_code: "1.2.10", ptrait: "Photosynthetic pathway"},
  {ptrait_code: "1.2.11", ptrait: "Leaf frost sensivity"},
  {ptrait_code: "1.2.12", ptrait: "Others"},
  {ptrait_code: "1.2.2", ptrait: "Leaf size"},
  {ptrait_code: "1.2.3", ptrait: "Leaf dry matter content"},
  {ptrait_code: "1.2.4", ptrait: "Leaf nitrogen concentration"},
  {ptrait_code: "1.2.5", ptrait: "Leaf Phosphorous concentration"},
  {ptrait_code: "1.2.6", ptrait: "physical strength of leaves"},
  {ptrait_code: "1.2.7", ptrait: "Phenolic content"},
  {ptrait_code: "1.2.8", ptrait: "Leaf lifespan"},
  {ptrait_code: "1.2.9", ptrait: "Leaf phenology"},
  {ptrait_code: "1.3", ptrait: "Stem traits"},
  {ptrait_code: "1.3.1", ptrait: "Stem specific density"},
  {ptrait_code: "1.3.2", ptrait: "Twig dry matter content"},
  {ptrait_code: "1.3.3", ptrait: "twig drying time"},
  {ptrait_code: "1.3.4", ptrait: "Shoot morphology"},
  {ptrait_code: "1.3.5", ptrait: "Bark thickness"},
  {ptrait_code: "1.3.6", ptrait: "Others"},
  {ptrait_code: "1.4", ptrait: "Belowground traits"},
  {ptrait_code: "1.4.1", ptrait: "Specific root length"},
  {ptrait_code: "1.4.2", ptrait: "time root diameter"},
  {ptrait_code: "1.4.3", ptrait: "Root depth distribution"},
  {ptrait_code: "1.4.4", ptrait: "95% rooting depth"},
  {ptrait_code: "1.4.5", ptrait: "Nutrient uptake strategy"},
  {ptrait_code: "1.4.6", ptrait: "Others"},
  {ptrait_code: "2", ptrait: "Regenerative Traits"},
  {ptrait_code: "2.1", ptrait: "Regenerative traits"},
  {ptrait_code: "2.1.1", ptrait: "Dispersal mode"},
  {ptrait_code: "2.1.2", ptrait: "Reproduction"},
  {ptrait_code: "2.1.3", ptrait: "Dispersal shape and size"},
  {ptrait_code: "2.1.4", ptrait: "Seed mass"},
  {ptrait_code: "2.1.5", ptrait: "Resprouting capacity"},
  {ptrait_code: "2.1.6", ptrait: "Seed production"},
  {ptrait_code: "2.1.7", ptrait: "Seed bank persistence"},
  {ptrait_code: "2.1.8", ptrait: "Flower lifespan"},
  {ptrait_code: "2.1.9", ptrait: "Others"},
  {ptrait_code: "3", ptrait: "Environmental Traits"},
  {ptrait_code: "3.1", ptrait: "Habitat preferences"},
  {ptrait_code: "3.1.1", ptrait: "Habitat naturalness"},
  {ptrait_code: "3.1.2", ptrait: "Light"},
  {ptrait_code: "3.1.3", ptrait: "Moisture"},
  {ptrait_code: "3.1.4", ptrait: "Nitrogen"},
  {ptrait_code: "3.1.5", ptrait: "Others"},
  {ptrait_code: "3.2", ptrait: "Stress tolerance"},
  {ptrait_code: "3.2.1", ptrait: "Chemical"},
  {ptrait_code: "3.2.2", ptrait: "Physical"},
  {ptrait_code: "3.2.3", ptrait: "Biological"},
  {ptrait_code: "3.2.4", ptrait: "Others"}
])

Nob.destroy_all

Nob.create([
  {nob_code: "1", nob: "Genetic"},
  {nob_code: "1.1", nob: "Allelic diversity"},
  {nob_code: "1.2", nob: "Inbreeding depression"},
  {nob_code: "1.3", nob: "Gene flow"},
  {nob_code: "1.4", nob: "Others"},
  {nob_code: "2", nob: "Species/population"},
  {nob_code: "2.1", nob: "Abundance/density"},
  {nob_code: "2.10", nob: "Size"},
  {nob_code: "2.11", nob: "Others"},
  {nob_code: "2.2", nob: "Bioaccumulation"},
  {nob_code: "2.3", nob: "Birth, death and recruitment"},
  {nob_code: "2.4", nob: "Dispersal"},
  {nob_code: "2.5", nob: "Frequency"},
  {nob_code: "2.6", nob: "Growth rates"},
  {nob_code: "2.7", nob: "Population structure (age ratio, sex ratio)"},
  {nob_code: "2.8", nob: "Phenology"},
  {nob_code: "2.9", nob: "Survivorship"},
  {nob_code: "3", nob: "Community"},
  {nob_code: "3.1", nob: "Biomass"},
  {nob_code: "3.10", nob: "Species diversity"},
  {nob_code: "3.11", nob: "Species richness"},
  {nob_code: "3.12", nob: "Species composition"},
  {nob_code: "3.13", nob: "Vegetation structure"},
  {nob_code: "3.14", nob: "Others"},
  {nob_code: "3.2", nob: "Occurence of indicator species"},
  {nob_code: "3.3", nob: "Occurence of rare species"},
  {nob_code: "3.4", nob: "Frequency of parasitism"},
  {nob_code: "3.5", nob: "Percentage cover"},
  {nob_code: "3.6", nob: "Amount of predation"},
  {nob_code: "3.7", nob: "Proportion of exotic species"},
  {nob_code: "3.8", nob: "Proportion of threatened and endangered species"},
  {nob_code: "3.9", nob: "Relative abundance of predators and prey"},
  {nob_code: "4", nob: "Ecosystem"},
  {nob_code: "4.1", nob: "Nutrients fixation"},
  {nob_code: "4.1.1", nob: "Carbon fixation"},
  {nob_code: "4.1.2", nob: "Nitrogen fixation"},
  {nob_code: "4.1.3", nob: "Others nutrient fixation"},
  {nob_code: "4.2", nob: "Decomposition rates"},
  {nob_code: "4.3", nob: "Disturbance intervals"},
  {nob_code: "4.4", nob: "Drainage patterns"},
  {nob_code: "4.5", nob: "Soil analysis"},
  {nob_code: "4.5.1", nob: "Texture"},
  {nob_code: "4.5.2", nob: "Organic matter"},
  {nob_code: "4.5.3", nob: "Nutrients"},
  {nob_code: "4.5.3.1", nob: "Carbon"},
  {nob_code: "4.5.3.10", nob: "K+"},
  {nob_code: "4.5.3.11", nob: "Fe"},
  {nob_code: "4.5.3.12", nob: "Heavy metal"},
  {nob_code: "4.5.3.13", nob: "Others"},
  {nob_code: "4.5.3.2", nob: "Inorganic nitrogen"},
  {nob_code: "4.5.3.3", nob: "Organic nitrogen"},
  {nob_code: "4.5.3.4", nob: "C:N"},
  {nob_code: "4.5.3.5", nob: "total anion"},
  {nob_code: "4.5.3.6", nob: "Total cation"},
  {nob_code: "4.5.3.7", nob: "P"},
  {nob_code: "4.5.3.8", nob: "S"},
  {nob_code: "4.5.3.9", nob: "Ca+"},
  {nob_code: "4.5.4", nob: "fisico quimica"},
  {nob_code: "4.5.4.1", nob: "pH"},
  {nob_code: "4.5.4.2", nob: "CIC"},
  {nob_code: "4.5.4.3", nob: "Electric conductivity"},
  {nob_code: "4.5.5", nob: "Erosion"},
  {nob_code: "4.5.5.1", nob: "Type"},
  {nob_code: "4.5.5.2", nob: "Severity"},
  {nob_code: "4.5.5.3", nob: "Soil erosion resistance"},
  {nob_code: "4.6", nob: "Topography"},
  {nob_code: "4.6.1", nob: "Large scale"},
  {nob_code: "4.6.1.1", nob: "Aspect"},
  {nob_code: "4.6.1.2", nob: "Slope"},
  {nob_code: "4.6.1.3", nob: "Others"},
  {nob_code: "4.6.2", nob: "Microsite"},
  {nob_code: "4.7", nob: "Water quality of runoff"},
  {nob_code: "4.8", nob: "Others"},
  {nob_code: "5", nob: "Landspace"},
  {nob_code: "5.1", nob: "Amount of edge"},
  {nob_code: "5.2", nob: "Connectivity"},
  {nob_code: "5.3", nob: "Fragmentation"},
  {nob_code: "5.4", nob: "Patch size"},
  {nob_code: "5.5", nob: "Proportion surrounded by different habitats"},
  {nob_code: "5.6", nob: "Others"}
])