# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Climate.destroy_all

Climate.create([
  {climate_code: "1", climate: "Equatorial Climates"},
  {climate_code: "1.1", climate: "Equatorial rainforest, fully humid"},
  {climate_code: "1.1.1", climate: "Equatorial rainforest, fully humid"},
  {climate_code: "1.2", climate: "Equatorial monsoon"},
  {climate_code: "1.2.1", climate: "Equatorial monsoon"},
  {climate_code: "1.3", climate: "Equatorial savannah with dry summer"},
  {climate_code: "1.3.1", climate: "Equatorial savannah with dry summer"},
  {climate_code: "1.4", climate: "Equatorial savannah with dry winter"},
  {climate_code: "1.4.1", climate: "Equatorial savannah with dry winter"},
  {climate_code: "2", climate: "Arid climates"},
  {climate_code: "2.1", climate: "Desert climate"},
  {climate_code: "2.1.1", climate: "Hot desert"},
  {climate_code: "2.1.2", climate: "Cold desert"},
  {climate_code: "2.1.3", climate: "Hot steppe"},
  {climate_code: "2.1.4", climate: "Cold steppe"},
  {climate_code: "2.2", climate: "Steppe climate"},
  {climate_code: "3", climate: "Warm temperate climates"},
  {climate_code: "3.1", climate: "Warm temperate climate, fully humid"},
  {climate_code: "3.1.1", climate: "Hot summer"},
  {climate_code: "3.1.2", climate: "Warm summer"},
  {climate_code: "3.1.3", climate: "Cool summer and cold winter"},
  {climate_code: "3.2", climate: "Warm temperate climate with dry summer"},
  {climate_code: "3.2.1", climate: "Hot summer"},
  {climate_code: "3.2.2", climate: "Warm summer"},
  {climate_code: "3.2.3", climate: "Cool summer and cold winter"},
  {climate_code: "3.3", climate: "Warm temperate climate with dry winter"},
  {climate_code: "3.3.1", climate: "Hot summer"},
  {climate_code: "3.3.2", climate: "Warm summer"},
  {climate_code: "3.3.3", climate: "Cool summer and cold winter"},
  {climate_code: "4", climate: "Snow climates"},
  {climate_code: "4.1", climate: "Snow climate, fully humid"},
  {climate_code: "4.1.1", climate: "Hot summer"},
  {climate_code: "4.1.2", climate: "Warm summer"},
  {climate_code: "4.1.3", climate: "Cool summer and cold winter"},
  {climate_code: "4.1.4", climate: "extremely continental"},
  {climate_code: "4.2", climate: "Snow climate with dry winter"},
  {climate_code: "4.2.1", climate: "Hot summer"},
  {climate_code: "4.2.2", climate: "Warm summer"},
  {climate_code: "4.2.3", climate: "Cool summer and cold winter"},
  {climate_code: "4.2.4", climate: "extremely continental"},
  {climate_code: "4.3", climate: "Snow climate with dry summer"},
  {climate_code: "4.3.1", climate: "Hot summer"},
  {climate_code: "4.3.2", climate: "Warm summer"},
  {climate_code: "4.3.3", climate: "Cool summer and cold winter"},
  {climate_code: "4.3.4", climate: "extremely continental"},
  {climate_code: "5", climate: "Polar climates"},
  {climate_code: "5.1", climate: "Tundra climate"},
  {climate_code: "5.1.1", climate: "Tundra climate"},
  {climate_code: "5.2", climate: "Frost climate"},
  {climate_code: "5.2.1", climate: "Frost climate"}
])

Landuse.destroy_all

Landuse.create([
  {landuse_code: "1", landuse: "Artificial surfaces"},
  {landuse_code: "1.1", landuse: "Urban fabric"},
  {landuse_code: "1.1.1", landuse: "Continuous urban fabric"},
  {landuse_code: "1.1.2", landuse: "Discontinuous urban fabric"},
  {landuse_code: "1.2", landuse: "Industrial, commercial and transport units"},
  {landuse_code: "1.2.1", landuse: "Industrial or commercial units"},
  {landuse_code: "1.2.2", landuse: "Road and rail networks and associated land"},
  {landuse_code: "1.2.3", landuse: "Port areas"},
  {landuse_code: "1.2.4", landuse: "Airports"},
  {landuse_code: "1.3", landuse: "Mine, dump and construction sites"},
  {landuse_code: "1.3.1", landuse: "Mineral extraction sites"},
  {landuse_code: "1.3.2", landuse: "Dump sites"},
  {landuse_code: "1.3.3", landuse: "Construction sites"},
  {landuse_code: "1.4", landuse: "Artificial, non-agricultural vegetated areas"},
  {landuse_code: "1.4.1", landuse: "Green urban areas"},
  {landuse_code: "1.4.2", landuse: "Sport and leisure facilities"},
  {landuse_code: "2", landuse: "Agricultural areas"},
  {landuse_code: "2.1", landuse: "Arable land"},
  {landuse_code: "2.1.1", landuse: "Non-irrigated arable land"},
  {landuse_code: "2.1.2", landuse: "Permanently irrigated land"},
  {landuse_code: "2.1.3", landuse: "Rice fields"},
  {landuse_code: "2.2", landuse: "Permanent crops"},
  {landuse_code: "2.2.1", landuse: "Vineyards"},
  {landuse_code: "2.2.2", landuse: "Fruit trees and berry plantations"},
  {landuse_code: "2.2.3", landuse: "Olive groves"},
  {landuse_code: "2.3", landuse: "Pastures"},
  {landuse_code: "2.3.1", landuse: "Pastures"},
  {landuse_code: "2.4", landuse: "Heterogeneous agricultural areas"},
  {landuse_code: "2.4.1", landuse: "Annual crops associated with permanent crops"},
  {landuse_code: "2.4.2", landuse: "Complex cultivation patterns"},
  {landuse_code: "2.4.3", landuse: "Land principally occupied by agriculture, with significant areas of natural vegetation"},
  {landuse_code: "2.4.4", landuse: "Agro-forestry areas"},
  {landuse_code: "3", landuse: "Forest and semi natural areas"},
  {landuse_code: "3.1", landuse: "Forests"},
  {landuse_code: "3.1.1", landuse: "Broad-leaved forest"},
  {landuse_code: "3.1.2", landuse: "Coniferous forest"},
  {landuse_code: "3.1.3", landuse: "Mixed forest"},
  {landuse_code: "3.2", landuse: "Scrub and/or herbaceous vegetation associations"},
  {landuse_code: "3.2.1", landuse: "Natural grasslands"},
  {landuse_code: "3.2.2", landuse: "Moors and heathland"},
  {landuse_code: "3.2.3", landuse: "Sclerophyllous vegetation"},
  {landuse_code: "3.2.4", landuse: "Transitional woodland-shrub"},
  {landuse_code: "3.3", landuse: "Open spaces with little or no vegetation"},
  {landuse_code: "3.3.1", landuse: "Beaches, dunes, sands"},
  {landuse_code: "3.3.2", landuse: "Bare rocks"},
  {landuse_code: "3.3.3", landuse: "Sparsely vegetated areas"},
  {landuse_code: "3.3.4", landuse: "Burnt areas"},
  {landuse_code: "3.3.5", landuse: "Glaciers and perpetual snow"},
  {landuse_code: "4", landuse: "Wetlands"},
  {landuse_code: "4.1", landuse: "Inland wetlands"},
  {landuse_code: "4.1.1", landuse: "Inland marshes"},
  {landuse_code: "4.1.2", landuse: "Peat bogs"},
  {landuse_code: "4.2", landuse: "Maritime wetlands"},
  {landuse_code: "4.2.1", landuse: "Salt marshes"},
  {landuse_code: "4.2.2", landuse: "Salines"},
  {landuse_code: "4.2.3", landuse: "Intertidal flats"},
  {landuse_code: "5", landuse: "Water bodies"},
  {landuse_code: "5.1", landuse: "Inland waters"},
  {landuse_code: "5.1.1", landuse: "Water courses"},
  {landuse_code: "5.1.2", landuse: "Water bodies"},
  {landuse_code: "5.2", landuse: "Marine waters"},
  {landuse_code: "5.2.1", landuse: "Coastal lagoons"},
  {landuse_code: "5.2.2", landuse: "Estuaries"},
  {landuse_code: "5.2.3", landuse: "Sea and ocean"}
])

Plantcommunity.destroy_all

Plantcommunity.create([
  {plantcommunity_code: "1",   plantcommunity: "Bosque denso (árboles de más de 5m cuyas copas se tocan)"},
  {plantcommunity_code: "1.1", plantcommunity: "Mayormente sempervirente"},
  {plantcommunity_code: "1.2", plantcommunity: "Mayormente deciduo"},
  {plantcommunity_code: "1.3", plantcommunity: "Extremadamente xeromórfico"},
  {plantcommunity_code: "2",   plantcommunity: "Bosque claro (Comunidad de árboles abierta)"},
  {plantcommunity_code: "2.1", plantcommunity: "Mayormente sempervirente"},
  {plantcommunity_code: "2.2", plantcommunity: "Mayormente deciduo"},
  {plantcommunity_code: "2.3", plantcommunity: "Extremadamente xeromórfico"},
  {plantcommunity_code: "3",   plantcommunity: "Matorral (denso o claro)"},
  {plantcommunity_code: "3.1", plantcommunity: "Mayormente sempervirente"},
  {plantcommunity_code: "3.2", plantcommunity: "Sempervirente aciculifoliado micrófilo claro (o denso)"},
  {plantcommunity_code: "3.3", plantcommunity: "Mayormente deciduo"},
  {plantcommunity_code: "3.4", plantcommunity: "Extremadamente xeromórfico (subdesierto)"},
  {plantcommunity_code: "4",   plantcommunity: "Matorral enano y comunidades relacionadas"},
  {plantcommunity_code: "4.1", plantcommunity: "Matorral enano mayormente sempervirente"},
  {plantcommunity_code: "4.2", plantcommunity: "Matorral enano mayormente deciduo"},
  {plantcommunity_code: "4.3", plantcommunity: "Matorral claro enano extremadamente xeromórfico"},
  {plantcommunity_code: "4.4", plantcommunity: "Tundra de arbustos enanos, líquenes y musgos"},
  {plantcommunity_code: "4.5", plantcommunity: "Formación de pantano turboso de musgos con arbustos enanos"},
  {plantcommunity_code: "5",   plantcommunity: "Vegetación herbácea"},
  {plantcommunity_code: "5.1", plantcommunity: "Vegetación graminoide alta"},
  {plantcommunity_code: "5.2", plantcommunity: "Vegetación graminoide de altura intermedia"},
  {plantcommunity_code: "5.3", plantcommunity: "Vegetación graminoide baja"},
  {plantcommunity_code: "5.4", plantcommunity: "Vegetación de forbias"},
  {plantcommunity_code: "5.5", plantcommunity: "Vegetación hidromórfica de agua dulce"}

])